name: CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    name: Ruff Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Run Ruff
        run: |
          pip install ruff
          ruff check .
  mypy:
    name: MyPy
    needs: ruff
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies and MyPy
        run: |
          pip install -r requirements.txt
          pip install mypy

      - name: Run MyPy
        run: |
          mypy --install-types --non-interactive app.py config.py models/ pages/ utils/
  test:
    name: Unit Tests Python ${{ matrix.python-version }} on ${{ matrix.os }}
    needs: ruff
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        python-version: [ "3.10", "3.11", "3.12", "3.13" ]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests with pytest
        run: |
          pytest -v
